Annotating prototype of bli_abort with BLIS_EXPORT_BLIS
Details:
- BLIS test application throws an error when built with dynamic
  library as "Undefined reference to bli_abort". This happens because
  bli_abort is hidden and cannot be linkable from outside. Annotating
  prototype with BLIS_EXPORT_BLAS to make it public.

Change-Id: I0d7aec046e8871ba6491024694ed06f883b005ac
AMD Internal: [CPUPL-1030]